# visual inertial state estimation and feature tracking results generated by maplab2 on euroc sequences.

eurocbags=(
machine_hall/MH_01_easy/MH_01_easy.bag
machine_hall/MH_02_easy/MH_02_easy.bag
machine_hall/MH_03_medium/MH_03_medium.bag
machine_hall/MH_04_difficult/MH_04_difficult.bag
machine_hall/MH_05_difficult/MH_05_difficult.bag
vicon_room1/V1_01_easy/V1_01_easy.bag
vicon_room1/V1_02_medium/V1_02_medium.bag
vicon_room1/V1_03_difficult/V1_03_difficult.bag
vicon_room2/V2_01_easy/V2_01_easy.bag
vicon_room2/V2_02_medium/V2_02_medium.bag
vicon_room2/V2_03_difficult/V2_03_difficult.bag)

eurocbags=(vicon_room2/V2_03_difficult/V2_03_difficult.bag)

datadir=/media/jhuai/BackupPlus/jhuai/data/euroc/ijrr_euroc_mav_dataset

resultdir=/home/jhuai/Desktop/temp/maplab2/euroc
exportscript=/media/jhuai/docker/bsplines_ws/src/lie_splines/bsplines_ceres/test/data/vimap_export.yaml
maplab_ws=/media/jhuai/docker/maplab2_ws
source $maplab_ws/devel/setup.bash
mkdir -p $resultdir
counter=0

for bag in ${eurocbags[@]}; do
    bn=$(basename -- "$bag")
    bn="${bn%.*}"
    rm -r $resultdir/$bn
    sed -i "/maplab2/c\  - $resultdir/$bn" $exportscript
    cmd="rosrun rovioli tutorial_euroc $resultdir/$bn $datadir/$bag --vio_nframe_sync_max_output_frequency_hz=10"
    echo $cmd
    $cmd
    rosrun maplab_console batch_runner --batch_control_file $exportscript
    ((counter++))
    # if [ $counter -gt 0 ]; then
    #     break
    # fi
done
