# visual inertial state estimation and feature tracking results generated by maplab2 on TUMVI sequences.

tumvibags=(room1
room2
room3
room4
room5
room6
slides1
slides2
slides3
corridor1
corridor2
corridor3
corridor4
corridor5
outdoors1
outdoors2
outdoors3
outdoors4
outdoors5
outdoors6
outdoors7
outdoors8
magistrale1
magistrale2
magistrale3
magistrale4
magistrale5
magistrale6)

datadir=/media/jhuai/BackupPlus/jhuai/data/tumvi/calibrated/512_16
resultdir=/home/jhuai/Desktop/temp/maplab2/tumvi
exportscript=/media/jhuai/docker/bsplines_ws/src/lie_splines/bsplines_ceres/test/data/vimap_export.yaml

maplab_ws=/media/jhuai/docker/maplab2_ws
source $maplab_ws/devel/setup.bash
mkdir -p $resultdir
counter=0
for bag in ${tumvibags[@]}; do
    bn=$(basename -- "$bag")
    bn="${bn%.*}"
    rm -r $resultdir/$bn
    sed -i "/maplab2/c\  - $resultdir/$bn" $exportscript
    cmd="rosrun rovioli tutorial_tumvi $resultdir/$bn $datadir/dataset-"$bag"_512_16.bag --vio_nframe_sync_max_output_frequency_hz=10"
    echo $cmd
    $cmd
    rosrun maplab_console batch_runner --batch_control_file $exportscript
    ((counter++))
    # if [ $counter -gt 0 ]; then
    #     break
    # fi
done

