#!/usr/bin/env bash
# Script to run ROVIOLI from a Euroc rosbag data source.
# Usage: tutorial_euroc <output save folder> <rosbag path> [<additional rovioli flags>]

LOCALIZATION_MAP_OUTPUT=$1
ROSBAG=$2
SENSOR_CALIBRATION="$ROVIO_CONFIG_DIR/euroc-stereo.yaml"
REST=$@

rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --v=2 \
  --sensor_calibration_file="$SENSOR_CALIBRATION" \
  --datasource_type="rosbag" \
  --save_map_folder="$LOCALIZATION_MAP_OUTPUT" \
  --optimize_map_to_localization_map=false \
  --map_builder_save_image_as_resources=false \
  --datasource_rosbag=$ROSBAG $REST
